version: "3"

services:
  worker:
    build:
      context: .
    command: python worker.py
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env
    networks:
      - storypool-network

  server:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    env_file:
      - ./.env
    networks:
      - storypool-network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: soon0729
      MYSQL_DATABASE: storypool
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - storypool-network

  redis:
    image: redis:8
    restart: always
    ports:
      - "6379:6379"
    networks:
      - storypool-network

volumes:
  mysql-data:

networks:
  storypool-network:
    driver: bridge
