global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'custom_watcher'
    static_configs:
      - targets: ['watcher:8000']
